name: Create and publish Docker image

on:
  push:
    branches: ['main']
    paths:
      - .github/workflows/**
      - Dockerfile
  schedule:
    # Weekly time picked randomly: "At 03:52 on Wednesday."
    - cron: '52 3 11 * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
  # Keep at least platform count of latest versions
  KEEP_LAST: 4

jobs:
  update-latest-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.PLATFORMS }}
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with: 
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          min-versions-to-keep: ${{ env.KEEP_LAST }}
          delete-only-untagged-versions: 'true'
